///////////////////////////////////////////////////////////
//  AMLHelper.cs
//  Implementation of the Class AMLHelper
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:19
//  Original author: Dennis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
using Bibliotheken.AMLEditorPlugin.Contracts;
using Bibliotheken.AMLEditorPlugin.Base;
using AMLHelperPlugin.Controller;
namespace AMLHelperPlugin.Controller {
	/// <summary>
	/// Diese Klasse implementiert die AML Plugin Schnittstelle.
	/// Die Methode "ActivatePlugin" wird bei Start des Plugins aus dem AML Editor
	/// heraus aufgerufen.
	/// </summary>
	public class AMLHelper : PluginBase, IAMLEditorPlugin {

		public AMLHelperPlugin.View.PluginWindow m_PluginWindow;
		public AMLHelperPlugin.Controller.ConfigurationManager m_ConfigurationManager;

		public AMLHelper(){

		}

		~AMLHelper(){

		}

		public AMLEditorPlugin.Contracts.PluginCommand ActivatePlugin{
			get;
			set;
		}

		public void Init(){

		}

		public override bool IsActive{
			get;
			set;
		}

		public override bool IsReactive{
			get;
			set;
		}

		public override bool IsReadonly{
			get;
			set;
		}

		/// 
		/// <param name="prm1"></param>
		/// <param name="prm2"></param>
		public override void PublishAutomationMLFileAndObject(string prm1, CAEX_ClassModel.CAEXBasicObject prm2){

		}

		/// 
		/// <param name="prm1"></param>
		protected override void TerminateCommandExecute(object prm1){

		}

		/// 
		/// <param name="prm1"></param>
		public void add_PluginActivated(System.EventHandler prm1){

		}

		/// 
		/// <param name="prm1"></param>
		public void ChangeAMLFilePath(string prm1){

		}

		/// 
		/// <param name="prm1"></param>
		public void ChangeSelectedObject(CAEX_ClassModel.CAEXBasicObject prm1){

		}

		public System.Collections.Generic.List`1<class AMLEditorPlugin.Contracts.PluginCommand> Commands{
			get;
			set;
		}

		public string DisplayName{
			get;
			set;
		}

		/// 
		/// <param name="prm1"></param>
		/// <param name="prm2"></param>
		public void ExecuteCommand(AMLEditorPlugin.Contracts.PluginCommandsEnum prm1, string prm2){

		}

		/// 
		/// <param name="prm1"></param>
		public void remove_PluginActivated(System.EventHandler prm1){

		}

		/// 
		/// <param name="prm1"></param>
		public void remove_PluginTerminated(System.EventHandler prm1){

		}

		public AMLEditorPlugin.Contracts.PluginCommand TerminatePlugin{
			get;
			set;
		}

	}//end AMLHelper

}//end namespace Controller