///////////////////////////////////////////////////////////
//  MenuEventHandler.cs
//  Implementation of the Class MenuEventHandler
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: Max
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
namespace AMLHelperPlugin.Controller {
	public class MenuEventHandler : EventHandler {

		public AMLHelperPlugin.View.MenuPanel m_MenuPanel;

		public MenuEventHandler(){

		}

		~MenuEventHandler(){

		}

		public void OnDoubleClick(){

		}

		public void OnKeyPress(){

		}

		public void OnMiddleMouseClick(){

		}

		public void OnRightClick(){

		}

	}//end MenuEventHandler

}//end namespace Controller