///////////////////////////////////////////////////////////
//  TabController.cs
//  Implementation of the Class TabController
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:22
//  Original author: Dennis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
using AMLHelperPlugin.Model;
using AMLHelperPlugin.Controller;
namespace AMLHelperPlugin.Controller {
	/// <summary>
	/// Ein Controller der sich um die Verwaltung (Öffnen, Schließen, anderes Element
	/// anzeigen) von Registerkarten kümmert.
	/// </summary>
	public class TabController {

		private CAEXTab currentTab;
		private Map <Long, CAEXTab> tabsById;
		public AMLHelperPlugin.View.PluginWindow m_PluginWindow;
		public AMLHelperPlugin.Model.ConcreteHistory m_ConcreteHistory;
		public AMLHelperPlugin.Controller.TabEventHandler m_TabEventHandler;

		public TabController(){

		}

		~TabController(){

		}

		/// 
		/// <param name="newTab"></param>
		public void ChangeCurrentTab(CAEXTab newTab){

		}

		/// <summary>
		/// Fügt einen neue Registerkarte in die Registerkartenleiste des Pluginfensters
		/// hinzu.
		/// Gibt true zurück wenn der Tab erfolgreich erstellt wurde.
		/// False, falls es nicht möglich war den Tab zu erstellen.
		/// </summary>
		/// <param name="caexElement"></param>
		public CAEXTab CreateNewTab(CAEXTab caexElement){

			return null;
		}

		/// <summary>
		/// Return the tab, that corresponds to the CAEXElement, if not found return NULL.
		/// </summary>
		/// <param name="caexElement"></param>
		public CAEXTab ExistsTabFor(CAEXTab caexElement){

			return null;
		}

		public CAEXTab GetCurrentTab(){

			return null;
		}

		/// 
		/// <param name="id"></param>
		public CAEXTab GetTab(long id){

			return null;
		}

		/// 
		/// <param name="caexElement"></param>
		public List <CAEXTab> GetTabsFor(CAEXTab caexElement){

			return null;
		}

	}//end TabController

}//end namespace Controller