///////////////////////////////////////////////////////////
//  TabEventHandler.cs
//  Implementation of the Class TabEventHandler
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:22
//  Original author: Max
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.Controller;
namespace AMLHelperPlugin.Controller {
	/// <summary>
	/// Stellt Methoden für Events in Tabs zur Verfügung.
	/// </summary>
	public class TabEventHandler : EventHandler {

		public AMLHelperPlugin.Controller.TabController m_TabController;

		public TabEventHandler(){

		}

		~TabEventHandler(){

		}

		/// <summary>
		/// Öffnet das Element auf das doppelt geklickt wurde in dem Tab in dem das
		/// Ereignis aufgetreten ist.
		/// </summary>
		public void OnDoubleClick(){

		}

		public void OnKeyPress(){

		}

		/// <summary>
		/// Öffnet das Element auf das doppelt geklickt wurde in einem neuen Tab.
		/// </summary>
		public void OnMiddleMouseClick(){

		}

		public void OnRightClick(){

		}

	}//end TabEventHandler

}//end namespace Controller