///////////////////////////////////////////////////////////
//  TreeEventHandler.cs
//  Implementation of the Class TreeEventHandler
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:22
//  Original author: Team
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.Controller;
namespace AMLHelperPlugin.Controller {
	/// <summary>
	/// Diese Klasse stellt Methoden für Usereingaben, die im TreePanel auftreten zur
	/// Verfügung.
	/// </summary>
	public class TreeEventHandler : EventHandler {

		private CAEXElement myObj;
		public AMLHelperPlugin.Controller.CAEXTreeView m_CAEXTreeView;



		~TreeEventHandler(){

		}

		public TreeEventHandler(){

		}

		/// 
		/// <param name="myObj"></param>
		public TreeEventHandler(CAEXElement myObj){

		}

		/// <summary>
		/// Öffnet das Element auf das doppelt geklickt wurde in der aktuellen
		/// Registerkarte.
		/// </summary>
		/// <param name="selectedNode"></param>
		public void OnDoubleClick(TreeNode selectedNode){

		}

		/// 
		/// <param name="selectedNode"></param>
		public void OnKeyPress(TreeNode selectedNode){

		}

		/// <summary>
		/// Öffnet das Element auf das doppelt geklickt wurde in einer neuen Registerkarte.
		/// 
		/// </summary>
		/// <param name="selectedNode"></param>
		public void OnMiddleMouseClick(TreeNode selectedNode){

		}

		/// <summary>
		/// Zeigt ein Kontextmenü beim geklickten Element.
		/// </summary>
		/// <param name="selectedNode"></param>
		public void OnRightClick(TreeNode selectedNode){

		}

	}//end TreeEventHandler

}//end namespace Controller