///////////////////////////////////////////////////////////
//  AttributeElement.cs
//  Implementation of the Class AttributeElement
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:19
//  Original author: Team
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
using Bibliotheken.Windows.ComponentModel;
namespace AMLHelperPlugin.ElementExtraction {
	public class AttributeElement : INotifyPropertyChanged {

		/// <summary>
		/// Die Eigenschaft, die diesen Attribut aktualisirt, benutzt die Funktion
		/// OnPropertyChanged
		/// </summary>
		private string dataType;
		/// <summary>
		/// Die Eigenschaft, die diesen Attribut aktualisirt, benutzt die Funktion
		/// OnPropertyChanged
		/// </summary>
		private string defaultValue;
		/// <summary>
		/// Die Eigenschaft, die diesen Attribut aktualisirt, benutzt die Funktion
		/// OnPropertyChanged
		/// </summary>
		private string description;
		/// <summary>
		/// Die Eigenschaft, die diesen Attribut aktualisirt, benutzt die Funktion
		/// OnPropertyChanged
		/// </summary>
		private short direction;
		/// <summary>
		/// Die Eigenschaft, die diesen Attribut aktualisirt, benutzt die Funktion
		/// OnPropertyChanged
		/// </summary>
		private string name;
		/// <summary>
		/// Schon vorhanden
		/// </summary>
		private PropertyChangedEventHandler propertyChanged;
		/// <summary>
		/// Die Eigenschaft, die diesen Attribut aktualisirt, benutzt die Funktion
		/// OnPropertyChanged
		/// </summary>
		private string value;
		public AMLHelperPlugin.View.InterfaceTabPanel m_InterfaceTabPanel;

		public AttributeElement(){

		}

		~AttributeElement(){

		}

		/// 
		/// <param name="propertyName"></param>
		private string OnPropertyChanged(string propertyName){

			return "";
		}

	}//end AttributeElement

}//end namespace ElementExtraction