///////////////////////////////////////////////////////////
//  InstanceElement.cs
//  Implementation of the Class InstanceElement
//  Generated by Enterprise Architect
//  Created on:      29-Jan-2016 11:58:55
//  Original author: abeid
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Bibliotheken.CAEX_ClassModel;
using AMLHelperPlugin.ElementExtraction;
namespace AMLHelperPlugin.ElementExtraction {
	/// <summary>
	/// Außer dem Name muss es auch möglich, ein internes Element in der Hierarchie
	/// hinzugefügt zu werden. Daher erweitert InstanceElement CAEXElement mit einer
	/// zusätzlicher Liste von internen Elementen, deren "setter" die Operation
	/// "OnPropertyChanged" verwendet.
	/// </summary>
	public class InstanceElement : CAEXTab {

		/// <summary>
		/// the setter uses the OnPropertyChanged operation from the Upper Class
		/// </summary>
		private ObservableCollection<InternalElementType> internalElements;

		public InstanceElement(){

		}

		~InstanceElement(){

		}

		/// 
		/// <param name="instance"></param>
		public void Init(InstanceHierarchyType instance){

		}

	}//end InstanceElement

}//end namespace ElementExtraction