///////////////////////////////////////////////////////////
//  InternalElement.cs
//  Implementation of the Class InternalElement
//  Generated by Enterprise Architect
//  Created on:      29-Jan-2016 11:58:56
//  Original author: abeid
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Bibliotheken.CAEX_ClassModel;
namespace AMLHelperPlugin.ElementExtraction {
	public class InternalElement {

		private List<InterfaceClassType> interfaces;
		private List<InternalElementType> internalElements;
		private List<SupportedRoleClassType> roleClasses;

		public InternalElement(){

		}

		~InternalElement(){

		}

		/// 
		/// <param name="internal"></param>
		public void Init(InternalLinkType internal){

		}

	}//end InternalElement

}//end namespace ElementExtraction