///////////////////////////////////////////////////////////
//  InterfaceElement.cs
//  Implementation of the Class InterfaceElement
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: Team
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Bibliotheken.CAEX_ClassModel;
using AMLHelperPlugin.ElementExtraction;
namespace AMLHelperPlugin.ElementExtraction {
	/// <summary>
	/// Außer dem Name muss es auch möglich,Attrubute in "InterfaceClassType" zu
	/// bearbeitet. Daher erweitert InstanceElement CAEXElement mit einer zusätzlicher
	/// Liste von "AttributElement", die innerlich INotifyPropertyChanged implementiert.
	/// 
	/// Bitte AttributPanel lesen
	/// </summary>
	public class InterfaceElement : CAEXTab {

		/// <summary>
		/// Jedes Element in dieser Liste ist als ein AttributPanel dargestellt, ist auch
		/// dynamisch
		/// </summary>
		private ObservableCollection<AttributeElement> attributes;
		public AMLHelperPlugin.ElementExtraction.AttributeElement m_AttributeElement;

		public InterfaceElement(){

		}

		~InterfaceElement(){

		}

		/// 
		/// <param name="interface"></param>
		public void Init(InterfaceClassType interface){

		}

	}//end InterfaceElement

}//end namespace ElementExtraction