///////////////////////////////////////////////////////////
//  InterfaceElement.cs
//  Implementation of the Class InterfaceElement
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: Team
///////////////////////////////////////////////////////////

using System;
using CAEX_ClassModel;

namespace AMLHelper.ElementExtraction
{



    /// <summary>
    /// Repräsentation eines Interfaces aus einer CAEX-Struktur, im AMLHelper
    /// </summary>
    public class SupportedRoleElement : CAEXElement
    {

        public string CompletePath;
        public string RoleName;
        private bool _isSelected;
        public SupportedRoleClassType type;

        public bool IsSelected
        {
            get { return _isSelected; }
            set { _isSelected = value; }
        }
       
        public SupportedRoleElement(SupportedRoleClassType interfaceType, bool selected)
        {
            CompletePath = interfaceType.RoleReference;
            RoleName = ParsePath(CompletePath);
            Name = RoleName;
            OriginalName = Name;
            NameChanged = false;
            IsSelected = selected;
            type = interfaceType;
        }

        private string ParsePath(string completePath)
        {
            return "..." + completePath.Substring(completePath.LastIndexOf("/", StringComparison.Ordinal));
        }
        public override string ToString()
        {
            if (Caex != null && Caex.Name.Exists())
            {
                return Caex.Name.Value;
            }
            else
            {
                return base.ToString();
            }
        }

    }//end InterfaceElement

}//end namespace ElementExtraction