///////////////////////////////////////////////////////////
//  AbstractInterfacePanel.cs
//  Implementation of the Class AbstractInterfacePanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:19
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace AMLHelperPlugin.View {
	/// <summary>
	/// Bietet eine abstrakte Schnittstelle für InterfacePanels an um spätere
	/// Erweiterbarkeit zu ermöglichen.
	/// </summary>
	public abstract class AbstractInterfacePanel {

		public AbstractInterfacePanel(){

		}

		~AbstractInterfacePanel(){

		}

	}//end AbstractInterfacePanel

}//end namespace View