///////////////////////////////////////////////////////////
//  AbstractInstancePanel.cs
//  Implementation of the Class AbstractInstancePanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:19
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace AMLHelperPlugin.View {
	/// <summary>
	/// Bietet eine abstrakte Schnittstelle für InstancePanels an um spätere
	/// Erweiterbarkeit zu ermöglichen.
	/// </summary>
	public abstract class AbstractInstancePanel {

		public AbstractInstancePanel(){

		}

		~AbstractInstancePanel(){

		}

	}//end AbstractInstancePanel

}//end namespace View