///////////////////////////////////////////////////////////
//  AttributePanel.cs
//  Implementation of the Class AttributePanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:19
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Das Panel in dem Attribute eines InternalElements in einer Tabelle zum
	/// Bearbeiten angezeigt werden.
	/// --------------------------------------------------------------------------------
	/// ------------
	/// Dieses "Panel" ist mit Instanzen der Klasse AttributeElement gebindet, in dem
	/// auch jedes "TextBox" mit dem entsprechenden Attribut gebindet.
	/// UpdateSourceTrigger=PropertyChanged.
	/// </summary>
	public class AttributePanel {

		private TextBox datatype;
		private TextBox defaultValue;
		private TextBox descprition;
		private TextBox direction;
		private TextBox name;
		private TextBox value;
		public AMLHelperPlugin.View.InstanceTabPanel m_InstanceTabPanel;

		public AttributePanel(){

		}

		~AttributePanel(){

		}

		public override void OnDoubleClickElement(){

		}

		public override void OnMiddleClickElement(){

		}

		public override void OnRightClickElement(){

		}

	}//end AttributePanel

}//end namespace View