///////////////////////////////////////////////////////////
//  CollapsiblePanel.cs
//  Implementation of the Class CollapsiblePanel
//  Generated by Enterprise Architect
//  Created on:      29-Jan-2016 11:58:54
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace AMLHelperPlugin.View {
	/// <summary>
	/// Ein Panel, das sich durch Klick auf den Titel des Panels zusammenklappen lässt
	/// und dadurch weniger Platz wegnimmt.
	/// </summary>
	public class CollapsiblePanel : Panel {

		private List <String> elements;
		/// <summary>
		/// Referenz zum Model um die Daten aus der XML Datei zu erhalten
		/// </summary>
		private string model;
		private bool open;
		private string title;

		public CollapsiblePanel(){

		}

		~CollapsiblePanel(){

		}

		/// 
		/// <param name="element"></param>
		public bool AddElement(String element){

			return false;
		}

		public List <String> GetElements(){

			return null;
		}

		/// <summary>
		/// Gibt den Titel des CollapsiblePanels zurück
		/// </summary>
		public String GetTitle(){

			return "";
		}

		/// <summary>
		/// Gibt zurück ob das Panel geöffnet ist (=true) oder geschlossen (=false)
		/// </summary>
		public bool IsOpen(){

			return false;
		}

		/// <summary>
		/// Minimiert das Panel. (Setzt Sichtbarkeit auf false)
		/// </summary>
		public void OnClickTitle(){

		}

		public void OnDoubleClickElement(){

		}

		public void OnMiddleClickElement(){

		}

		public void OnRightClickElement(){

		}

		public bool RemoveElement(){

			return false;
		}

	}//end CollapsiblePanel

}//end namespace View