///////////////////////////////////////////////////////////
//  ConcretePanelFactory.cs
//  Implementation of the Class ConcretePanelFactory
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:20
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
namespace AMLHelperPlugin.View {
	public class ConcretePanelFactory : AbstractPanelFactory {

		public ConcretePanelFactory(){

		}

		~ConcretePanelFactory(){

		}

	}//end ConcretePanelFactory

}//end namespace View