///////////////////////////////////////////////////////////
//  HierarchieBaum; bitte Name ergänzen!.cs
//  Implementation of the Class HierarchieBaum; bitte Name ergänzen!
//  Generated by Enterprise Architect
//  Created on:      29-Jan-2016 11:58:55
//  Original author: Dennis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace AMLHelperPlugin.View {
	/// <summary>
	/// Struktur für den InstanceHierarchie-Baum.
	/// (Gegeben durch VS, Name bitte nachtragen).
	/// </summary>
	public class HierarchieBaum; bitte Name ergänzen! {

		public HierarchieBaum; bitte Name ergänzen!(){

		}

		~HierarchieBaum; bitte Name ergänzen!(){

		}

	}//end HierarchieBaum; bitte Name ergänzen!

}//end namespace View