///////////////////////////////////////////////////////////
//  HistoryTab.cs
//  Implementation of the Class HistoryTab
//  Generated by Enterprise Architect
//  Created on:      29-Jan-2016 11:58:55
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace AMLHelperPlugin.View {
	/// <summary>
	/// Ein Tab, der sich merkt, welches Element vorher darin geöffnet war.
	/// </summary>
	public abstract class HistoryTab {

		public HistoryTab(){

		}

		~HistoryTab(){

		}

		/// <summary>
		/// Gibt das aktuelle Objekt in der Historie zurück.
		/// </summary>
		public abstract CAEXObject GetCurrentObject();

		/// <summary>
		/// Gibt das nächste Element der Historie zurück. Sollte dieses nicht existieren
		/// wird null zurückgegeben.
		/// </summary>
		public abstract CAEXObject GetNextInHistory();

		/// <summary>
		/// Gitb das vorherige Element in der Historie zurück, Null falls dieses nicht
		/// existiert.
		/// </summary>
		public abstract CAEXObject GetPreviousInHistory();

		/// <summary>
		/// Lädt den Inhalt des Historie Tabs erneut.
		/// </summary>
		public void Reload(){

		}

	}//end HistoryTab

}//end namespace View