///////////////////////////////////////////////////////////
//  IEPanel.cs
//  Implementation of the Class IEPanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:20
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Panel, das InternalElements auflistet, ohne jedoch die Möglichkeit anzubieten,
	/// weitere InternalElements hinzuzufügen.
	/// </summary>
	public class IEPanel {

		private TextBox internalElements;
		public AMLHelperPlugin.View.InternalElementTabPanel m_InternalElementTabPanel;

		public IEPanel(){

		}

		~IEPanel(){

		}

		public override void OnDoubleClickElement(){

		}

		public override void OnMiddleClickElement(){

		}

		public override void OnRightClickElement(){

		}

	}//end IEPanel

}//end namespace View