///////////////////////////////////////////////////////////
//  InstanceIEPanel.cs
//  Implementation of the Class InstanceIEPanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Panel, das InternalElements anzeigt, und die Möglichkeit bietet weitere
	/// InternalElements von der geladenen SystenUnitClassLib hinzuzufügen.
	/// --------------------------------------------------------------------------------
	/// -----------
	/// Das TextBox internalElements ist mit dem
	/// ObservableCollection<InternalElementClassType> in "InstanceElement" gebindet.
	/// UpdateSourceTrigger=Explicit
	/// </summary>
	public class InstanceIEPanel {

		private Button addInternalElement;
		private TextBox internalElements;
		private TextBox newInternalElement;
		public AMLHelperPlugin.View.InternalElementTabPanel m_InternalElementTabPanel;

		public InstanceIEPanel(){

		}

		~InstanceIEPanel(){

		}

		public override void OnDoubleClickElement(){

		}

		public override void OnMiddleClickElement(){

		}

		public override void OnRightClickElement(){

		}

	}//end InstanceIEPanel

}//end namespace View