///////////////////////////////////////////////////////////
//  InstanceHierachiePanel.cs
//  Implementation of the Class InstanceHierachiePanel
//  Generated by Enterprise Architect
//  Created on:      29-Jan-2016 11:58:55
//  Original author: Dennis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Panel, welcher den InstanceHierachie-Baum beinhaltet.
	/// </summary>
	public class InstanceHierachiePanel : CollapsiblePanel {

		public HierarchieBaum; bitte Name ergänzen! m_HierarchieBaum; bitte Name ergänzen!;
		public AMLHelperPlugin.View.Scrollbar m_Scrollbar;

		public InstanceHierachiePanel(){

		}

		~InstanceHierachiePanel(){

		}

	}//end InstanceHierachiePanel

}//end namespace View