///////////////////////////////////////////////////////////
//  InstanceTabPanel.cs
//  Implementation of the Class InstanceTabPanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Tab in dem Instanzen angezeigt werden.
	/// </summary>
	public class InstanceTabPanel {

		private InstanceIEPanel instancePanel;
		public AMLHelperPlugin.View.TabPanel m_TabPanel;

		public InstanceTabPanel(){

		}

		~InstanceTabPanel(){

		}

	}//end InstanceTabPanel

}//end namespace View