///////////////////////////////////////////////////////////
//  InterfaceTabPanel.cs
//  Implementation of the Class InterfaceTabPanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.ElementExtraction;
using AMLHelperPlugin.View;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Tab in dem Interfaces angezeigt werden.
	/// </summary>
	public class InterfaceTabPanel {

		private List<AttributePanel> attributes;
		public AMLHelperPlugin.ElementExtraction.AttributeElement m_AttributeElement;
		public AMLHelperPlugin.View.TabPanel m_TabPanel;

		public InterfaceTabPanel(){

		}

		~InterfaceTabPanel(){

		}

	}//end InterfaceTabPanel

}//end namespace View