///////////////////////////////////////////////////////////
//  InterfacePanel.cs
//  Implementation of the Class InterfacePanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Zeigt die Interfaces des InternalElements an, das zu diesem Panel gehört.
	/// </summary>
	public class InterfacePanel {

		private TextBox interfaces;
		public AMLHelperPlugin.View.InterfaceTabPanel m_InterfaceTabPanel;

		public InterfacePanel(){

		}

		~InterfacePanel(){

		}

		public override void OnDoubleClickElement(){

		}

		public override void OnMiddleClickElement(){

		}

		public override void OnRightClickElement(){

		}

	}//end InterfacePanel

}//end namespace View