///////////////////////////////////////////////////////////
//  MenuPanel.cs
//  Implementation of the Class MenuPanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: nadim
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
using AMLHelperPlugin.Controller;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Panel der Menu-Leiste
	/// </summary>
	public class MenuPanel {

		private ToolStripMenuItem CloseItem;
		private ToolStripMenuItem NewItem;
		private ToolStripMenuItem OpenItem;
		private ToolStripMenuItem SaveAsItem;
		private ToolStripMenuItem SaveItem;
		private ToolStrip toolStrip;
		public AMLHelperPlugin.View.PluginWindow m_PluginWindow;
		public AMLHelperPlugin.Controller.MenuEventHandler m_MenuEventHandler;



		~MenuPanel(){

		}

		/// <summary>
		/// Privater Konstrukter um Instanziierung zu verhindern
		/// </summary>
		private MenuPanel(){

		}

		/// <summary>
		/// Gibt das MenuPanel zurück, sofern es existiert. Andernfalls wird eine neue
		/// Instanz angelegt.
		/// </summary>
		public static MenuPanel GetMenuPanel(){

			return null;
		}

		/// <summary>
		/// Wird aufgerufen wenn auf ein Element in der Menüleiste geklickt wird.
		/// </summary>
		public void OnElementClick(){

		}

	}//end MenuPanel

}//end namespace View