///////////////////////////////////////////////////////////
//  PluginWindow.cs
//  Implementation of the Class PluginWindow
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: Dennis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace AMLHelperPlugin.View {
	/// <summary>
	/// Das Hauptfenster in dem sich alle anderen Panele befinden.
	/// </summary>
	public class PluginWindow {

		public PluginWindow(){

		}

		~PluginWindow(){

		}

		public void Close(){

		}

		/// 
		/// <param name="path"></param>
		private string CreateConfigPath(string path){

			return "";
		}

		public void Init(){

		}

		public void Reload(){

		}

		/// 
		/// <param name="path"></param>
		public bool Save(string path){

			return false;
		}

	}//end PluginWindow

}//end namespace View