///////////////////////////////////////////////////////////
//  RoleClassPanel.cs
//  Implementation of the Class RoleClassPanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.View;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Panel, das die RoleClasses des geladenen InternalElements anzeigt.
	/// </summary>
	public class RoleClassPanel {

		private List<CheckBox> supportedRoleClasses;
		public AMLHelperPlugin.View.InternalElementTabPanel m_InternalElementTabPanel;

		public RoleClassPanel(){

		}

		~RoleClassPanel(){

		}

		public override void OnDoubleClickElement(){

		}

		public override void OnMiddleClickElement(){

		}

		public override void OnRightClickElement(){

		}

	}//end RoleClassPanel

}//end namespace View