///////////////////////////////////////////////////////////
//  Scrollbar.cs
//  Implementation of the Class Scrollbar
//  Generated by Enterprise Architect
//  Created on:      29-Jan-2016 11:58:56
//  Original author: Dennis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace AMLHelperPlugin.View {
	/// <summary>
	/// Scrollbar, in welcher der InstanceHierachie-Baum ist.
	/// (Gegeben durch VS).
	/// </summary>
	public class Scrollbar {

		public Scrollbar(){

		}

		~Scrollbar(){

		}

	}//end Scrollbar

}//end namespace View