///////////////////////////////////////////////////////////
//  TabPanel.cs
//  Implementation of the Class TabPanel
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:22
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.ElementExtraction;
using AMLHelperPlugin.View;
using AMLHelperPlugin.Controller;
namespace AMLHelperPlugin.View {
	/// <summary>
	/// Dieses "Panel" ist mit dem "CAEXElement" gebindet, auﬂerdem ist der TextBox
	/// "name" mit dem Attribute "name" im "CAEXElement" gebindet.
	/// </summary>
	public abstract class TabPanel {

		/// <summary>
		/// Der Name des CAEXObjects wird in dieser Textbox angezeigt.
		/// </summary>
		private TextBox name;
		public AMLHelperPlugin.ElementExtraction.CAEXTab m_CAEXTab;
		public AMLHelperPlugin.View.AbstractPanelFactory m_AbstractPanelFactory;
		public AMLHelperPlugin.Controller.TabController m_TabController;

		public TabPanel(){

		}

		~TabPanel(){

		}

		/// 
		/// <param name="tab"></param>
		public TabPanel(CAEXTab tab){

		}

	}//end TabPanel

}//end namespace View