///////////////////////////////////////////////////////////
//  ConcreteTabPersistence.cs
//  Implementation of the Class ConcreteTabPersistence
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:20
//  Original author: Max
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AMLHelperPlugin.Model;
namespace AMLHelperPlugin.Model {
	public class ConcreteTabPersistence : AbstractTabPersistence {

		public ConcreteTabPersistence(){

		}

		~ConcreteTabPersistence(){

		}

		/// 
		/// <param name="filePath"></param>
		public override List <Tab> LoadOldTabs(String filePath){

			return null;
		}

		/// 
		/// <param name="filePath"></param>
		public override bool SaveCurrentTabs(String filePath){

			return false;
		}

	}//end ConcreteTabPersistence

}//end namespace Model