///////////////////////////////////////////////////////////
//  History.cs
//  Implementation of the Interface History
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:20
//  Original author: kelln_000
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace AMLHelperPlugin.Model {
	/// <summary>
	/// Diese Schnittstelle ordnet Elemente in einem Verlauf an, ähnlich wie bei einem
	/// (Web-) Browser.
	/// </summary>
	public interface History  {

		/// <summary>
		/// Fügt ein Element zur Historie hinzu.
		/// </summary>
		/// <param name="element"></param>
		bool AddElementToHistory(Object element);

		/// <summary>
		/// Gibt das nächste Element in der Historie zurück. null wenn dieses nicht
		/// exisitiert.
		/// </summary>
		Object GetNextElement();

		/// <summary>
		/// Gibt das vorherige Element zurück. Gibt null zurück, falls es dieses nicht gibt.
		/// 
		/// </summary>
		Object GetPreviousElement();
	}//end History

}//end namespace Model