///////////////////////////////////////////////////////////
//  InterfaceElement.cs
//  Implementation of the Class InterfaceElement
//  Generated by Enterprise Architect
//  Created on:      30-Jan-2016 10:51:21
//  Original author: Team
///////////////////////////////////////////////////////////

using System.Collections.ObjectModel;
using CAEX_ClassModel;

namespace AMLHelper.ElementExtraction {

	/// <summary>
	/// Repräsentation eines Interfaces aus einer CAEX-Struktur, im AMLHelper
	/// </summary>
	public class InterfaceElement : CAEXElement {	

		public InterfaceElement(InterfaceClassType interfaceType){
            Name = interfaceType.Name.Value;
            OriginalName = interfaceType.Name.Value;
            NameChanged = false;
            Caex = interfaceType;
            ParentElements = new ObservableCollection<CAEXElement>();
            ChildElements = new ObservableCollection<CAEXElement>();
		}

	}//end InterfaceElement

}//end namespace ElementExtraction